### ISSUE TITLE
[Bug] Always failed to reload

### ISSUE THREAD

**Issue by Hiusi** [quiqueck/WorldWeaver#14]
### What happened?

A bug happened!

### WorldWeaver

21.0.11

### Fabric API

0.100.8

### Fabric Loader

0.16.0

### Minecraft

1.21

### Relevant log output

```shell
[16:02:42] [Server thread/INFO]: [BTDK: Reloading!]
[16:02:43] [Worker-ResourceReload-1/ERROR]: Unable to building bartering table
[16:02:43] [Worker-ResourceReload-1/INFO]: 🗣 Register Easy NPC /easy_npc commands for Easy NPC ...
[16:02:43] [Worker-ResourceReload-1/INFO]: Reflections took 30 ms to scan 1 urls, producing 73 keys and 466 values
[16:02:43] [Worker-ResourceReload-3/ERROR]: Couldn't load tag mes:common_avoid as it is missing following references: mes:tower (from mes), mes:decoration (from mes)
[16:02:43] [Worker-ResourceReload-1/ERROR]: Couldn't load tag minecraft:undead as it is missing following references: #easy_npc:skeletons (from easy_npc), #easy_npc:zombies (from easy_npc)
[16:02:43] [Worker-ResourceReload-1/ERROR]: Couldn't load tag minecraft:sensitive_to_smite as it is missing following references: #minecraft:undead (from vanilla)
[16:02:43] [Worker-ResourceReload-1/ERROR]: Couldn't load tag minecraft:can_breathe_under_water as it is missing following references: #minecraft:undead (from vanilla)
[16:02:43] [Worker-ResourceReload-1/ERROR]: Couldn't load tag minecraft:inverted_healing_and_harm as it is missing following references: #minecraft:undead (from vanilla)
[16:02:43] [Worker-ResourceReload-1/ERROR]: Couldn't load tag minecraft:wither_friends as it is missing following references: #minecraft:undead (from vanilla)
[16:02:43] [Worker-ResourceReload-1/ERROR]: Couldn't load tag minecraft:ignores_poison_and_regen as it is missing following references: #minecraft:undead (from vanilla)
[16:02:43] [Server thread/WARN]: Failed to execute reload
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.betterx.wover.biome.impl.BiomeBootstrapContextImpl.prepareTags(org.betterx.wover.tag.api.event.context.TagBootstrapContext)" because "context" is null
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.betterx.wover.biome.impl.BiomeBootstrapContextImpl.prepareTags(org.betterx.wover.tag.api.event.context.TagBootstrapContext)" because "context" is null
        at org.betterx.wover.biome.impl.BiomeManagerImpl.onBootstrapTags(BiomeManagerImpl.java:95) ~[wover-biome-21.0.11-e8a6ab12fa38b879.jar:?]
        at org.betterx.wover.tag.impl.TagRegistryImpl.lambda$emitLoadEvent$0(TagRegistryImpl.java:90) ~[wover-tag-21.0.11-97684ab8134e2f2a.jar:?]
        at org.betterx.wover.events.impl.EventImpl.lambda$emit$0(EventImpl.java:15) ~[wover-events-21.0.11-40929d164ffa777e.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.betterx.wover.events.impl.EventImpl.emit(EventImpl.java:15) ~[wover-events-21.0.11-40929d164ffa777e.jar:?]
        at org.betterx.wover.tag.impl.TagRegistryImpl.emitLoadEvent(TagRegistryImpl.java:90) ~[wover-tag-21.0.11-97684ab8134e2f2a.jar:?]
        at org.betterx.wover.tag.impl.TagManagerImpl.didLoadTagMap(TagManagerImpl.java:108) ~[wover-tag-21.0.11-97684ab8134e2f2a.jar:?]
        at net.minecraft.class_3503.modify$fci000$wover-tag$be_modifyTags(class_3503.java:1525) ~[server-intermediary.jar:?]
        at net.minecraft.class_3503.method_33176(class_3503.java:128) ~[server-intermediary.jar:?]
        at net.minecraft.class_3505.method_33181(class_3505.java:46) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
```

**Comment by quiqueck** [comment]
Could you please post a list of other installed mods as well?

**Comment by Hiusi** [comment]
Sorry, yes
```
	- accessories 1.0.0-beta.26+1.21
	- adventurez 1.4.21
	- afkplus 1.5.0
	- alloy_forgery 2.3.1+1.21
	- amplified_nether 1.2.5
	- appleskin 3.0.5+mc1.21
	- architectury 13.0.6
	- armoroftheages 1.4.1
	- armourers_workshop 3.0.0-beta.12
	- artifacts 12.0.4
	- audioplayer 1.21-1.10.2
	- automodpack-bootstrap 1.0.0
	- badpackets 0.8.1
	- balm-fabric 21.0.14
	- bb_preload_world 1.2
	- bclib 21.0.10
	- beautify 1.2.1+1.21
	- betterend 21.0.6
	- betterfurniture 1.21-1.0.5
	- betternether 21.0.9
	- biomesoplenty 21.0.0.13
	- blabber 1.7.1
	- bosses_of_mass_destruction 1.10.1-1.21
	- cardinal-components 6.1.1
	- carryon 2.2.1
	- charmofundying 9.0.0+1.21
	- chococraft 0.11.5
	- chunksending 1.21-2.8
	- chunky 1.4.16
	- cloth-config 15.0.128
	- clumps 18.0.0.2
	- collective 7.80
	- coroutil 1.21.0-1.3.7
	- crafttweaker 20.0.19
	- craterlib 2.0.2
	- creativecore 2.12.6
	- cristellib 1.2.7
	- croptopia 3.0.9
	- ctov 3.5.1
	- cupboard 1.21-2.7
	- debugify 1.21+1.0
	- deuf_refabricated 1.1.0
	- disenchanting_table 3.0.2
	- doggytalents 1.18.27
	- dynamiclights 1.8.3+mod
	- easy_npc 5.4.2
	- elytraslot 9.0.0+1.21
	- emi 1.1.10+1.21+fabric
	- emojiful 5.1.4
	- enhancedgroups 1.21-1.6.0
	- epherolib 1.2.0-1.20.6
	- fabric-api 0.100.8+1.21
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	- fabricloader 0.16.0
	- fallingtree 1.21.0.6
	- fancymenu 3.2.5
	- fastasyncworldsave 1.21-2.0
	- faux-custom-entity-data 12.0.1
	- ferritecore 7.0.0
	- forgeconfigapiport 21.0.7
	- friendsandfoes 2.0.15
	- ftbfiltersystem 21.0.0
	- ftblibrary 2100.1.4
	- ftbquests 2100.1.4
	- ftbteams 2100.1.0
	- ftbxmodcompat 3.2.1
	- fuji 1.4.3
	- fwaystones 3.3.3+mc1.21
	- geckolib 4.5.7
	- glitchcore 2.0.0.2
	- gobber2 2.10.23
	- grassoverhaul 1.0.0
	- guarding 1.21-2.7.0
	- handcrafted 4.0.1
	- hopobettermineshaft 1.2.7
	- hopobetterruinedportal 1.4.3
	- hopobetterunderwaterruins 1.2.0
	- invview 1.4.15-1.20.5+
	- jade 15.1.5+fabric
	- java 21
	- jei 19.7.0.90
	- kiwi 15.1.0+fabric
	- knightquest 1.4.2
	- konkrete 1.9.9
	- letmedespawn 1.3.1
	- lithium 0.12.7
	- lithostitched 1.2.5
	- lootr 0.9.35.88
	- luckperms 5.4.137
	- macawsroofsbop 1.21-1.0
	- mcwdoors 1.1.1
	- mcwfences 1.1.2
	- mcwfencesbop 1.21-1.0
	- mcwfurnitures 3.3.0
	- mcwholidays 1.1.0
	- mcwlights 1.1.1
	- mcwroofs 2.3.1
	- mcwtrpdoors 1.1.3
	- mcwwindows 2.3.2
	- melius-vanish 1.5.6+1.21
	- melody 1.0.10
	- mes 1.3.2-1.21-fabric
	- midnightlib 1.5.7
	- minecraft 1.21
	- mixintrace 1.1.1+1.17
	- mns 1.0.2-1.21-fabric
	- modernfix 5.19.0+mc1.21
	- monolib 1.3.0
	- mr_beyondenchant 1.5.0
	- mr_catenary 1.3
	- mr_dungeons_andtaverns 1-v4.3
	- mr_katters_structures 2.0
	- mr_neoenchant 5.6.0
	- mr_yggdrasil_structure 1.4.0
	- mru 0.4.4+1.21
	- mss 1.1.2-1.21-fabric
	- mvs 4.1.3-1.21-fabric
	- mythicmetals 0.20.0+1.21-alpha5
	- natures_spirit 1.6.0-1.21
	- naturescompass 1.21-2.2.6-fabric
	- necronomicon 1.4.2
	- neruina 2.1.1
	- nightautoconfig 1.0.6
	- nochatreports 1.21-v2.8.0
	- noisium 2.2.1+mc1.21
	- openpartiesandclaims 0.23.2
	- owo 0.12.11+1.21
	- packetfixer 1.4.1
	- paxi 1.21-Fabric-5.0.0
	- ping-wheel 1.9.1
	- placeholder-api 2.4.1+1.21
	- polymer-bundled 0.9.9+1.21
	- polymorph 1.0.4+1.21
	- puzzleslib 21.0.18
	- regions_unexplored 0.5.6.1
	- repurposed_structures 7.5.4+1.21-fabric
	- resourcefullib 3.0.9
	- rewardz 1.0.3
	- sereneseasons 10.0.0.2
	- sketch 1.21-1.2.0
	- smoothchunk 1.21-3.6
	- snowrealmagic 11.0.2+fabric
	- snowundertrees 2.4.0+1.21
	- spark 1.10.73
	- sparsestructures 2.2.0
	- starterkit 7.1
	- structureessentials 1.21-3.4
	- t_and_t 1.13.2
	- tclayer 3.10.0+beta.5
	- tectonic 2.4.0
	- terrablender 4.0.0.1
	- totw_modded fabric-1.21-1.0.5
	- trashslot 21.0.2
	- travelersbackpack fabric-1.21-10.0.5
	- universal-graves 3.4.3+1.21
	- uselessreptile 0.7.4.2-1.21
	- vanityslots 1.4.1+1.21
	- veinmining 5.0.0-beta+1.21
	- voicechat 1.21-2.5.19
	- watut 1.21.0-1.1.3
	- worldedit 7.3.5+6880-8ba3d89
	- wover 21.0.11
	- xaerominimap 24.2.1
	- xaeroworldmap 1.38.8
	- yungsapi 1.21-Fabric-5.0.0
```
	
Also full log:
https://mclo.gs/2oqBwln

**Comment by ShiftySpace** [comment]
Same is happening to me.

**Comment by Taimoor-Tariq** [comment]
Having same issue. Server crashes whenever the `/reload` command is run.
I need to reload my datapacks and im unable to do so.

Here is the crash report:
https://gist.github.com/Taimoor-Tariq/30ce0dbb06026c510fa95e3c01046530

**Comment by Veloxotl** [comment]
### WorldWeaver
21.0.13
### Fabric API
0.115.4+1.21.1
### Fabric Loader
0.16.13
### Minecraft
1.21.1
### Relevant log output
```[23:32:41] [Worker-Main-1/ERROR]: Couldn't load tag wover:vegetation/plant as it is missing following references: #wover:vegetation/vine (from wover-tag)
[23:32:41] [Server thread/WARN]: Failed to execute reload
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.betterx.wover.biome.impl.BiomeBootstrapContextImpl.prepareTags(org.betterx.wover.tag.api.event.context.TagBootstrapContext)" because "context" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.betterx.wover.biome.impl.BiomeBootstrapContextImpl.prepareTags(org.betterx.wover.tag.api.event.context.TagBootstrapContext)" because "context" is null
	at knot/org.betterx.wover.biome.impl.BiomeManagerImpl.onBootstrapTags(BiomeManagerImpl.java:95) ~[wover-biome-21.0.13-ecfa0e39366be3d1.jar:?]
	at knot/org.betterx.wover.tag.impl.TagRegistryImpl.lambda$emitLoadEvent$0(TagRegistryImpl.java:95) ~[wover-tag-21.0.13-75893af4281a3b83.jar:?]
	at knot/org.betterx.wover.events.impl.EventImpl.lambda$emit$0(EventImpl.java:15) ~[wover-events-21.0.13-9c200a761df289a9.jar:?]
	at java.base/java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at knot/org.betterx.wover.events.impl.EventImpl.emit(EventImpl.java:15) ~[wover-events-21.0.13-9c200a761df289a9.jar:?]
	at knot/org.betterx.wover.tag.impl.TagRegistryImpl.emitLoadEvent(TagRegistryImpl.java:95) ~[wover-tag-21.0.13-75893af4281a3b83.jar:?]
	at knot/org.betterx.wover.tag.impl.TagManagerImpl.didLoadTagMap(TagManagerImpl.java:108) ~[wover-tag-21.0.13-75893af4281a3b83.jar:?]
	at knot/net.minecraft.class_3503.modify$baa000$wover-tag$wover_modifyTags(class_3503.java:525) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3503.method_33176(class_3503.java:128) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_3505.method_33181(class_3505.java:46) ~[client-intermediary.jar:?]
	... 7 more
[23:32:41] [Render thread/INFO]: [System] [CHAT] Reload failed; keeping old data
``` 
### Other Mods
N/A

#14 #18 #21 #22 seem to all have the same main issue with data pack reload, and the issue still persists even without any other mods present. So I don't think this is a compatibility issue as tagged. I've provided a log below of the entire process of creating a new world and then attempting to reload data packs with `/reload` in game.
https://mclo.gs/boWfspn

Edit: I am not a modder by any means but looking around in the code, I was wondering if this snippet of code might need to be corrected to `(ctx)` instead of `(null)` ? Since all of the above snippets read as `final BiomeBootstrapContextImpl context = initContext(ctx);`

```
private void prepareBiomeTags(TagBootstrapContext<Biome> ctx) {
        final BiomeBootstrapContextImpl context = initContext(null);
        context.prepareTags(ctx);
    }
```
From path `WorldWeaver/wover-biome-api/src/main/java/org/betterx/wover/datagen/api/provider/multi/WoverBiomeProvider.java`
