### ISSUE TITLE
[Bug] Datapack Reload Fails

### ISSUE THREAD

**Issue by Lord600** [quiqueck/WorldWeaver#18]
### What happened?

Datapack reloads continue to fail, can't enable OR disable any datapack. World Weaver throws an exception every reload.

### WorldWeaver

21.0.13

### Fabric API

0.106.00

### Fabric Loader

0.16.9

### Minecraft

1.21

### Relevant log output

```shell
[11:52:34] [Server thread/INFO]: [Wooff: Enabling data pack [file/enchancement_strongly_enchanted.zip (world)]]
[11:52:34] [Server thread/INFO]: Generated runtime SERVER_DATA for pack supplementaries:generated_pack (Supplementaries) in: 4 ms
[11:52:34] [Worker-ResourceReload-0/ERROR]: Couldn't parse element minecraft:loot_table/supplementaries:blocks/urn_loot/urn_loot - No key value in MapLike[{"type":"minecraft:loot_table","weight":1,"quality":5,"name":"supplementaries:blocks/urn_loot/epic"}]; No key value in MapLike[{"type":"minecraft:loot_table","weight":7,"quality":2,"name":"supplementaries:blocks/urn_loot/rare"}]; No key value in MapLike[{"type":"minecraft:loot_table","weight":32,"quality":-2,"name":"supplementaries:blocks/urn_loot/uncommon"}]; No key value in MapLike[{"type":"minecraft:loot_table","weight":60,"quality":-5,"name":"supplementaries:blocks/urn_loot/common"}]
[11:52:35] [Worker-ResourceReload-0/ERROR]: Couldn't parse element minecraft:loot_table/supplementaries:inject/end_city_stasis - Failed to parse either. First: No key components in MapLike[{"function":"set_components","tag":"{StoredEnchantments:[{lvl:1s,id:\"supplementaries:stasis\"}]}"}]; Second: Not a json array: {"function":"set_components","tag":"{StoredEnchantments:[{lvl:1s,id:\"supplementaries:stasis\"}]}"}
[11:52:35] [Worker-ResourceReload-0/ERROR]: Couldn't parse element minecraft:loot_table/supplementaries:inject/test - Failed to get element ResourceKey[moonlight:map_marker / supplementaries:igloo]
[11:52:35] [Worker-ResourceReload-0/ERROR]: Couldn't parse element minecraft:loot_table/supplementaries:blocks/fine_wood_slab - Failed to parse either. First: Unknown registry key in ResourceKey[minecraft:root / minecraft:block]: supplementaries:cabin_siding_slab; Second: Not a json array: {"condition":"minecraft:block_state_property","block":"supplementaries:cabin_siding_slab","properties":{"type":"double"}}; Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: supplementaries:cabin_siding_slab
[11:52:35] [Worker-ResourceReload-0/ERROR]: Couldn't parse element minecraft:loot_table/supplementaries:inject/temple_spikes - Failed to parse either. First: Unknown registry key in ResourceKey[minecraft:root / minecraft:loot_function_type]: supplementaries:set_charges; Second: Not a json array: {"function":"supplementaries:set_charges","damage":{"min":0.2,"max":0.9}}; Failed to parse either. First: Not a JSON object: [{"type":"minecraft:potion_content","potion":"minecraft:poison"}]; Second: Not a json array: {"function":"set_components","components":[{"type":"minecraft:potion_content","potion":"minecraft:poison"}]}
[11:52:35] [Worker-ResourceReload-0/ERROR]: Couldn't parse element minecraft:loot_table/supplementaries:blocks/fine_wood - Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: supplementaries:cabin_siding
[11:52:35] [Worker-ResourceReload-0/ERROR]: Couldn't parse element minecraft:loot_table/supplementaries:blocks/fine_wood_stairs - Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: supplementaries:cabin_siding
[11:52:35] [Worker-ResourceReload-0/ERROR]: Unable to building bartering table
[11:52:35] [Worker-ResourceReload-0/ERROR]: Couldn't parse element minecraft:loot_table/supplementaries:blocks/urn_loot/epic - Failed to parse either. First: Unknown registry key in ResourceKey[minecraft:root / minecraft:loot_function_type]: supplementaries:random_enchantment; Second: Not a json array: {"function":"supplementaries:random_enchantment","enchantments":"#minecraft:curse"}; Failed to parse either. First: Unknown registry key in ResourceKey[minecraft:root / minecraft:loot_function_type]: supplementaries:random_enchantment; Second: Not a json array: {"function":"supplementaries:random_enchantment","enchantments":"#minecraft:curse"}
[11:52:35] [Worker-ResourceReload-0/ERROR]: Couldn't parse element minecraft:loot_table/supplementaries:blocks/urn_loot/rare - Failed to parse either. First: Unknown registry key in ResourceKey[minecraft:root / minecraft:loot_function_type]: supplementaries:random_enchantment; Second: Not a json array: {"function":"supplementaries:random_enchantment","enchantments":"#minecraft:curse"}; Failed to parse either. First: No key enchantments in MapLike[{"function":"supplementaries:curse_loot"}]; No key chance in MapLike[{"function":"supplementaries:curse_loot"}]; Second: Not a json array: {"function":"supplementaries:curse_loot"}
[11:52:35] [Worker-ResourceReload-0/WARN]: Found loot table element validation problem in {minecraft:loot_table/minecraft:entities/husk}.pools[2].entries[0]: Unknown loot table called husks_drop_sand:entities/husk
[11:52:35] [Worker-ResourceReload-0/WARN]: Found loot table element validation problem in {minecraft:loot_table/minecraft:entities/villager}.pools[2].entries[0]: Unknown loot table called villager_death:entities/villager
[11:52:35] [Worker-ResourceReload-0/WARN]: Found loot table element validation problem in {minecraft:loot_table/minecraft:entities/bat}.pools[2].entries[0]: Unknown loot table called bat_membranes:entities/bat
[11:52:35] [Worker-ResourceReload-0/WARN]: Found loot table element validation problem in {minecraft:loot_table/minecraft:entities/player}.pools[1].entries[0]: Unknown loot table called graves:entities/player
[11:52:35] [Worker-ResourceReload-0/WARN]: Found loot table element validation problem in {minecraft:loot_table/minecraft:entities/shulker}.pools[2].entries[0]: Unknown loot table called double_shulker_shells:entities/shulker
[11:52:35] [Worker-ResourceReload-0/WARN]: Found loot table element validation problem in {minecraft:loot_table/supplementaries:blocks/urn}.pools[1].entries[0]: Unknown loot table called supplementaries:blocks/urn_loot/urn_loot
[11:52:35] [Server thread/WARN]: Failed to execute reload
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "org.betterx.wover.biome.impl.BiomeBootstrapContextImpl.prepareTags(org.betterx.wover.tag.api.event.context.TagBootstrapContext)" because "context" is null
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.betterx.wover.biome.impl.BiomeBootstrapContextImpl.prepareTags(org.betterx.wover.tag.api.event.context.TagBootstrapContext)" because "context" is null
        at knot/org.betterx.wover.biome.impl.BiomeManagerImpl.onBootstrapTags(BiomeManagerImpl.java:95) ~[wover-biome-21.0.13-ecfa0e39366be3d1.jar:?]
        at knot/org.betterx.wover.tag.impl.TagRegistryImpl.lambda$emitLoadEvent$0(TagRegistryImpl.java:95) ~[wover-tag-21.0.13-75893af4281a3b83.jar:?]
        at knot/org.betterx.wover.events.impl.EventImpl.lambda$emit$0(EventImpl.java:15) ~[wover-events-21.0.13-9c200a761df289a9.jar:?]
        at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at knot/org.betterx.wover.events.impl.EventImpl.emit(EventImpl.java:15) ~[wover-events-21.0.13-9c200a761df289a9.jar:?]
        at knot/org.betterx.wover.tag.impl.TagRegistryImpl.emitLoadEvent(TagRegistryImpl.java:95) ~[wover-tag-21.0.13-75893af4281a3b83.jar:?]
        at knot/org.betterx.wover.tag.impl.TagManagerImpl.didLoadTagMap(TagManagerImpl.java:108) ~[wover-tag-21.0.13-75893af4281a3b83.jar:?]
        at knot/net.minecraft.class_3503.modify$efe000$wover-tag$wover_modifyTags(class_3503.java:2025) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3503.method_33176(class_3503.java:128) ~[server-intermediary.jar:?]
        at knot/net.minecraft.class_3505.method_33181(class_3505.java:46) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 6 more
```

### Other Mods

```shell
Alamanac - 1.0.2
antixray - 1.4.6
Appleskin - 3.0.6
RPG Series Archers - 2.1.1
Architectury - 13.0.8
ArmorPoser - 6.1.3
Artifacts - 12.0.6
AzureLibArmor 2.3.13
Balm - 21.0.20
BCLib - 21.0.13
Better End - 21.0.11
Better Nether - 21.0.11
Better Combat - 2.0.3
Chunky - 1.4.16
Cloth Config - 15.0.140
Copper Hopper - 0.10.0
Dragon Loot - 1.1.7
Enchancement - r12
Enchanted Vertical Slabs - 2.3
Expanded Storage - 14.1.5
Fabric API - 0.106.0
Fabric Language Kotlin - 2.0.21
Farmers Delight 2.1.9
Ferrite Core - 7.0.2
Forge Config API Port - 21.1.1
Frozen Lib - 1.9.3
Inmis - 2.8.1
Jamlib - 1.2.2
JEI - 19.21.0.247
Krypton - 0.2.8
Let Me Despawn - 1.4.4
Lithium - 0.13.1
Modern Fix - 5.19.5
Moonlight - 2.15.13
Mutant Monster - 21.1.0
RPG Series Paladins - 2.1.1
playerAnimator - 2.0.0 - alpha1
PuzzlesLib - 21.1.22
Ranged Weapon API - 2.0.4
Right Click Harvest - 4.4.1
RPG Series Rogues - 2.1.0
Runes - 1.0.3
Shield API - 2.0.2
Silk - 1.10.7
Simple Copper Pipes - 2.0.3
Simple Hats - 0.3.2
Spark - 1.10.109
Enhanced Spawners - 1.2.8
Spell Engine - 1.1.2
Spell Power Attributes - 1.0.5
Structure Pool API - 1.1.3
Supplementaries - 3.0.8-alpha
Trinkets - 3.10.0
Vein Miner Enchant - 2.2.0
Vein Miner - 2.1.5
View Distance Fix - 1.0.2
Simple Voice Chat - 2.5.25
Waystones - 21.1.5
RPG Series Wizards - 2.1.0
World Weaver - 21.0.13
Youre In Grave Danger - 2.4.11
```

**Comment by Lord600** [comment]
This log output also seems very similar to #14
